---
# Lint YAML with ryl
name: Lint YAML

run-name: >
  ${{
    github.event_name == 'pull_request' && 'PR' ||
    (
      github.event_name == 'push' &&
      (contains(github.event.head_commit.message, 'Merge') || contains(github.event.head_commit.message, '(#'))
    ) && 'Merge' ||
    github.event_name == 'push' && 'Direct' ||
    github.event_name == 'schedule' && 'Cron' ||
    github.event_name
  }}
  ${{ github.event.pull_request.number && format(' #{0}', github.event.pull_request.number) || '' }}
  ${{ (github.actor && github.actor != 'github-actions[bot]') && format(' by @{0}', github.actor) || '' }} -
  ${{ github.workflow }} on ${{ github.head_ref || github.ref_name }} -
  ${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}

on:  # ryl disable-line rule:truthy
  pull_request:
    paths:
      - '**.yml'
      - '**/*ryl.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    name: Run ryl
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: 🔍 Get changed files
        id: filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d  # v4.0.3
        with:
          filters: |
            yaml:
              - added|modified: '**.yml'
              - added|modified: '**.yaml'
            rylconf:
              - added|modified: '{.,}ryl.toml'
              - added|modified: '.config/{.,}ryl.toml'
          list-files: escape
      - name: ⬇️ Install the latest version of uv
        if: steps.filter.outputs.yaml == 'true' || steps.filter.outputs.rylconf == 'true'
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          cache-dependency-glob: ''
          enable-cache: true
          # renovate: datasource=github-releases depName=astral-sh/uv
          version: 0.12.5
      - name: 🔍 Lint changed YAML files with ryl
        if: steps.filter.outputs.yaml == 'true' && steps.filter.outputs.rylconf == 'false'
        shell: bash
        run: uvx --config-file .config/uv.toml ryl ${{ steps.filter.outputs.markdown_files }}
      - name: 🔍 Lint all YAML files with ryl when ".ryl.toml" is updated
        if: steps.filter.outputs.rylconf == 'true'
        shell: bash
        run: uvx --config-file .config/uv.toml ryl .
