---
# Dependency Review
name: Dependency Review

run-name: >
  ${{ github.event_name }}
  ${{ github.event.pull_request.number && format(' #{0}', github.event.pull_request.number) || '' }}
  by @${{ github.actor }} -
  ${{ github.workflow }} on ${{ github.head_ref || github.ref_name }} -
  ${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}

on:  # ryl disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: 🔬 Dependency review
        uses: actions/dependency-review-action@v5.0.0
