name: Build Docusaurus

run-name: "${{ github.workflow }} - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request:
    paths:
      - website/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docusaurus:
    name: Build Docusaurus
    defaults:
      run:
        working-directory: ./website
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: ⚙️ Enable corepack
        run: corepack enable
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "yarn"
          cache-dependency-path: "./website/yarn.lock"
          node-version-file: "./website/.node-version"
      - name: 🧶 Yarn install
        run: yarn install --immutable
      - name: 🔨 Node.js build
        run: node --run build
