name: Lint GitHub workflows with zizmor

run-name: "${{ github.workflow }} - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request:
    paths:
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workflows:
    name: Run zizmor latest via PyPI
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: 🔍 Get changed files
        id: filter
        uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c # v4.0.0
        with:
          filters: |
            workflows:
              - added|modified: '.github/workflows/**'
          list-files: escape
      - name: ⬇️ Install the latest version of uv
        if: steps.filter.outputs.workflows == 'true'
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
        with:
          cache-dependency-glob: ""
          enable-cache: true
      - name: 🔍 Run zizmor
        if: steps.filter.outputs.workflows == 'true'
        run: |
          uvx zizmor --format plain --offline --min-confidence low --min-severity low \
          --config ./.config/zizmor.yml \
          ${{ steps.filter.outputs.workflows_files }}
