name: Lint GitHub workflows with zizmor

run-name: '${{ github.workflow }} - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}'

on:
  pull_request:
    paths:
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workflows:
    name: Run zizmor latest via PyPI
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: 🔍 Get changed files
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            workflows:
              - added|modified: '.github/workflows/**'
          list-files: escape
      - name: ⬇️ Install the latest version of uv
        if: steps.filter.outputs.workflows == 'true'
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
      - name: 🔍 Run zizmor
        if: steps.filter.outputs.workflows == 'true'
        run: |
          uvx zizmor --format plain --offline --min-confidence low --min-severity low \
          ${{ steps.filter.outputs.workflows_files }}
