---
# Dependency Review
name: Dependency Review

run-name: >
  ${{
    github.event_name == 'pull_request' && 'PR' ||
    (
      github.event_name == 'push' &&
      (contains(github.event.head_commit.message, 'Merge') || contains(github.event.head_commit.message, '(#'))
    ) && 'Merge' ||
    github.event_name == 'push' && 'Direct' ||
    github.event_name == 'schedule' && 'Cron' ||
    github.event_name
  }}
  ${{ github.event.pull_request.number && format(' #{0}', github.event.pull_request.number) || '' }}
  ${{ (github.actor && github.actor != 'github-actions[bot]') && format(' by @{0}', github.actor) || '' }} -
  ${{ github.workflow }} on ${{ github.head_ref || github.ref_name }} -
  ${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}

on:  # ryl disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: 🔬 Dependency review
        uses: actions/dependency-review-action@v5.0.0
