name: Lint markdown with rumdl

run-name: "${{ github.workflow }} - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request:
    paths:
      - "**.md"
      - "**/*rumdl.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Run rumdl
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: 🔍 Get changed files
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            markdown:
              - added|modified: '**.md'
            rumdlconf:
              - added|modified: '{.,}rumdl.toml'
              - added|modified: '.config/{.,}rumdl.toml'
          list-files: escape
      - name: ⬇️ Install the latest version of uv
        if: steps.filter.outputs.markdown == 'true' || steps.filter.outputs.rumdlconf == 'true'
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
        with:
          cache-dependency-glob: ""
          enable-cache: true
      - name: 🔍 Lint changed markdown files with rumdl
        if: steps.filter.outputs.markdown == 'true' && steps.filter.outputs.rumdlconf == 'false'
        shell: bash
        run: uvx rumdl check ${{ steps.filter.outputs.markdown_files }}
      - name: 🔍 Lint all markdown files with rumdl when ".rumdl.toml" is updated
        if: steps.filter.outputs.rumdlconf == 'true'
        shell: bash
        run: uvx rumdl check .
