---
# Build Docusaurus
name: Build Docusaurus

run-name: >
  ${{
    github.event_name == 'pull_request' && 'PR' ||
    (
      github.event_name == 'push' &&
      (contains(github.event.head_commit.message, 'Merge') || contains(github.event.head_commit.message, '(#'))
    ) && 'Merge' ||
    github.event_name == 'push' && 'Direct' ||
    github.event_name
  }}
  ${{ github.event.pull_request.number && format(' #{0}', github.event.pull_request.number) || '' }}
  by @${{ github.actor }} -
  ${{ github.workflow }} on ${{ github.head_ref || github.ref_name }} -
  ${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}

on:  # ryl disable-line rule:truthy
  pull_request:
    paths:
      - website/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docusaurus:
    name: Build Docusaurus
    defaults:
      run:
        working-directory: ./website
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: ⚙️ Enable corepack
        # zizmor: ignore[adhoc-packages]
        run: |
          if ! command -v corepack &>/dev/null; then
            npm install --global corepack@0.35.0
          fi
          corepack enable
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
          node-version-file: ./website/.node-version
      - name: 🧶 Yarn install
        run: yarn install --immutable
      - name: 🔨 Node.js build
        run: node --run build
