name: Lint GitHub workflows with zizmor

run-name: "${{ github.workflow }} - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request:
    paths:
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workflows:
    name: Run zizmor latest via PyPI
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      - name: 🛎️ GitHub checkout branch "${{ github.head_ref || github.ref_name }}"
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: 🔍 Get changed files
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            workflows:
              - added|modified: '.github/workflows/**'
          list-files: escape
      - name: ⬇️ Install the latest version of uv
        if: steps.filter.outputs.workflows == 'true'
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          cache-dependency-glob: ""
          enable-cache: true
      - name: 🔍 Run zizmor
        if: steps.filter.outputs.workflows == 'true'
        run: |
          uvx zizmor --format plain --offline --min-confidence low --min-severity low \
          --config ./.config/zizmor.yml \
          ${{ steps.filter.outputs.workflows_files }}
