name: 'Dependency Review'

on:
  pull_request:
    paths:
      - website/**

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
